GET http://localhost:4000/myshop/product
Authorization: 21f251f0-714e-11ed-b4c8-c30c9f3a3f10
####

POST   http://localhost:4000/myshop/product
Authorization: 21f251f0-714e-11ed-b4c8-c30c9f3a3f10
Content-Type: application/json

{
    "name": "G-shock 5GT",
    "slug":"gs5gt"
}
###

DELETE http://localhost:4000/myshop/9
Authorization: 21f251f0-714e-11ed-b4c8-c30c9f3a3f10
####

PUT  http://localhost:4000/listtodo/done/2
Authorization: ec508050-6593-11ed-971a-9fe465821d86
####

POST  http://localhost:4000/login
Content-Type: application/json

{
    "username":"lockheart",
    "password":"031090Ph"
}
####
POST  http://localhost:4000/create
Content-Type: application/json

{
    "username":"lockheart",
    "password":"031090Ph",
    "email":"ph.hoangloc@gmail.com"
}

POST  http://localhost:4000/myshop
Authorization: 87b83410-714d-11ed-8920-43e143bd3b52
Content-Type: application/json

{
    "brand": "DW",
    "cover":"DW.png"
}
###

DELETE http://localhost:4000/myshop/product/1
Authorization: 21f251f0-714e-11ed-b4c8-c30c9f3a3f10